[package]
name = "test-v0_5"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.99"
serde_json = "1.0.143"
wit-bindgen = "0.44.0"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
