# all jobs can be interrupted, e.g. when a newer pipeline for the same branch starts
default:
  interruptible: true

stages:
  - test
  - image_build
  - image_test

variables:
  CONTAINER_PORT: 8081

generate_version:
  stage: test
  image: registry.gitlab.aleph-alpha.de/enterprise-readiness/shared-images/gitlab-ci/common:latest
  script:
    - echo VERSION=$(date "+%Y_%m_%d_%H_%M_%S") >> build.env
  artifacts:
    reports:
      dotenv: build.env

cargo_clippy:
  stage: test
  image: rust:latest
  script:
    - rustup component add clippy;
    - cargo clippy --workspace --all-targets --all-features

cargo_test:
  stage: test
  image: rust:latest
  script:
    - cargo test -- --skip i_

image_build:
  stage: image_build
  image: registry.gitlab.aleph-alpha.de/enterprise-readiness/shared-images/gitlab-ci/common:latest
  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:my_section[collapsed=true]\r\e[0KBuild image"
    - >
      podman build \
        --ulimit nofile=$(ulimit -n):$(ulimit -n) \
        --layers \
        --cache-to $CI_REGISTRY_IMAGE/cache \
        --cache-from $CI_REGISTRY_IMAGE/cache \
        --cache-ttl=24h \
        -f Containerfile \
        --label "com.aleph-alpha.git-hash"=$CI_COMMIT_SHORT_SHA \
        --label "com.aleph-alpha.image-id"=$VERSION \
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA \
        --progress=plain \
        .
    - podman push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - echo -e "\e[0Ksection_end:`date +%s`:my_section\r\e[0K"

container_test:
  stage: image_test
  image: registry.gitlab.aleph-alpha.de/enterprise-readiness/shared-images/gitlab-ci/common:latest
  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - sh -x ./tests/test-container.sh $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# TODO: replace with actual integraton tests
integration_test:
  stage: image_test
  image: registry.gitlab.aleph-alpha.de/enterprise-readiness/shared-images/gitlab-ci/common:latest
  services:
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      alias: $CI_PROJECT_NAME
  script:
    - sh -x ./tests/test-image.sh $CONTAINER_PORT $CI_PROJECT_NAME
