include:
  - project: "engineering/vulnerability-scanner"
    file: "pipeline-templates/sbom_vulnerability_scan.v1.yml"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

# all jobs can be interrupted, e.g. when a newer pipeline for the same branch starts
default:
  interruptible: true

stages:
  - test
  - image_build
  - image_test
  - image_publish

variables:
  ARTIFACTORY_HOST: "alephalpha.jfrog.io"
  ARTIFACTORY_URL: "https://${ARTIFACTORY_HOST}"
  ARTIFACTORY_REPO: pharia-kernel-images
  CONTAINER_PORT: 8081

cargo_clippy:
  stage: test
  image: rust:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - rustup component add clippy
    - cargo clippy --workspace --all-targets --all-features

cargo_test:
  stage: test
  image: rust:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - rustup target add wasm32-wasi
    - ./build-skill.sh
    - ./build-skill-py.sh
    - cargo test

image_build:
  stage: image_build
  image: registry.gitlab.aleph-alpha.de/enterprise-readiness/shared-images/gitlab-ci/common:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:my_section[collapsed=true]\r\e[0KBuild image"
    - >
      podman build \
        --ulimit nofile=$(ulimit -n):$(ulimit -n) \
        --layers \
        --cache-to $CI_REGISTRY_IMAGE/cache \
        --cache-from $CI_REGISTRY_IMAGE/cache \
        --cache-ttl=24h \
        -f Containerfile \
        --label "com.aleph-alpha.git-hash"=$CI_COMMIT_SHORT_SHA \
        --label "com.aleph-alpha.image-id"=$(image_id) \
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA \
        --progress=plain \
        .
    - podman push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - echo -e "\e[0Ksection_end:`date +%s`:my_section\r\e[0K"

sbom_vulnerability_scan:
  extends: .sbom_vulnerability_scan
  stage: image_test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        ARTIFACT_NAME: $CI_PROJECT_NAME
        FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_SECURITY_SCAN == "true"
      variables:
        ARTIFACT_NAME: $CI_PROJECT_NAME:latest
        FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest

container_test:
  stage: image_test
  image: registry.gitlab.aleph-alpha.de/enterprise-readiness/shared-images/gitlab-ci/common:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - sh -x ./tests/test-container.sh $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# TODO: replace with actual integration tests
integration_test:
  stage: image_test
  image: registry.gitlab.aleph-alpha.de/enterprise-readiness/shared-images/gitlab-ci/common:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  services:
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      alias: $CI_PROJECT_NAME
  script:
    - sh -x ./tests/test-image.sh $CONTAINER_PORT $CI_PROJECT_NAME

image_publish:
  stage: image_publish
  image: registry.gitlab.aleph-alpha.de/enterprise-readiness/shared-images/gitlab-ci/common:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_SECURITY_SCAN == "true"
      when: never
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: $ARTIFACTORY_URL
  script:
    - podman login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - IMAGE_ID=$(podman inspect $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA | jq -r '.[].Config.Labels["com.aleph-alpha.image-id"]')
    - podman tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $ARTIFACTORY_HOST/$ARTIFACTORY_REPO/$CI_PROJECT_NAME:latest
    - podman tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $ARTIFACTORY_HOST/$ARTIFACTORY_REPO/$CI_PROJECT_NAME:$IMAGE_ID
    - podman logout $CI_REGISTRY
    - JFROG_ACCESS_TOKEN=$(get_jfrog_access_token $GITLAB_OIDC_TOKEN)
    - JFROG_ACCESS_TOKEN_SUBJECT=$(extract_access_token_subject $JFROG_ACCESS_TOKEN)
    - podman login --username "$JFROG_ACCESS_TOKEN_SUBJECT" --password $JFROG_ACCESS_TOKEN $ARTIFACTORY_URL/$ARTIFACTORY_REPO
    - podman push $ARTIFACTORY_HOST/$ARTIFACTORY_REPO/$CI_PROJECT_NAME:latest
    - podman push $ARTIFACTORY_HOST/$ARTIFACTORY_REPO/$CI_PROJECT_NAME:$IMAGE_ID
