[namespaces.pharia-kernel-team]
# The URL to the configuration listing the Skills of this namespace
# PhariaKernel will use the contents of the `NAMESPACES__PHARIA_KERNEL_TEAM__CONFIG_ACCESS_TOKEN` environment variable to access (authorize) the config
config-url = "https://gitlab.aleph-alpha.de/api/v4/projects/966/repository/files/config.toml/raw?ref=main"

# Registry to load skills from
# PhariaKernel will use the contents of the `NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_USER` and `NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_PASSWORD` environment variables to access (authorize) the registry
registry = "registry.gitlab.aleph-alpha.de"
base-repository = "engineering/pharia-skills/skills"
