[project]
team = "pharia-kernel"
repository = "pharia-kernel"
contact = "markus.klein@aleph-alpha.com"

# For now must keep this and .trivyignore in sync
#
# Example
# [trivy.CVE-2017-0144]
# base_score = "high"
# description = "allows remote attackers to execute arbitrary code via crafted packets, aka 'Windows SMB Remote Code Execution Vulnerability.'"
# acceptance = "We are not worried about wannacry we think security is a tinfoil hat wearing alarmist weirdo"
# date = 2025-02-26
# triaged_by = "flip flop"
