{{- if not .Values.backwardsCompatibility }}
{{- template "pharia-common.deployment" (dict "customTemplate" "pharia-kernel.deployment" "rootContext" $ "resourceContextName" "") -}}
{{- end -}}

{{- define "pharia-kernel.deployment" -}}
## Define overrides for your resource here
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
{{- end }}
