{{- template "pharia-common.deployment" (dict "customTemplate" "pharia-kernel.deployment" "rootContext" $ "resourceContextName" "") -}}
{{- define "pharia-kernel.deployment" -}}
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
{{- end }}
