{{- template "pharia-common.deployment" (dict "value" (list . "pharia-kernel.deployment") "context" $) -}}
{{- define "pharia-kernel.deployment" -}}
## Define overrides for your resource here
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
{{- end -}}
