apiVersion: v1
kind: ConfigMap
metadata:
  name: pharia-kernel-operator-config
data:
  operator-config.toml: |
    {{- if or .Values.defaultNamespacesEnabled .Values.namespaces }}
    {{- if .Values.defaultNamespacesEnabled }}
    [namespaces.assistant]
    {{- with index $.Values "pharia-assistant-api" }}
    config_url = {{ printf "%s.%s.svc.cluster.local/skills/skill-config" .fullnameOverride $.Release.Namespace | quote }}
    {{- end }}

    [namespaces.assistant.registry]
    type = "oci"
    registry = "alephalpha.jfrog.io"
    repository = "assistant-skills"
    user_env_var = "ALEPH_ALPHA_OCI_SKILL_REGISTRY_USER"
    password_env_var = "ALEPH_ALPHA_OCI_SKILL_REGISTRY_PASSWORD"
    {{- end }}

    {{- if .Values.namespaces }}
    {{- range $k, $v := .Values.namespaces }}
    [namespaces.{{ $k }}]
    config_url = {{ $v.config_url | quote }}
    {{- if $v.config_access_token_env_var }}
    config_access_token_env_var = {{ $v.config_access_token_env_var | quote }}
    {{- end }}

    [namespaces.{{ $k }}.registry]
    type = "oci"
    registry = {{ $v.registry | quote }}
    repository = {{ $v.repository | quote }}
    user_env_var = {{ $v.user_env_var | quote }}
    password_env_var = {{ $v.password_env_var | quote }}
    {{ end }}
    {{- end }}
    {{- else }}
    [namespaces]
    {{- end }}
