apiVersion: v1
kind: ConfigMap
metadata:
  name: pharia-kernel-operator-config
data:
  operator-config.toml: |
    {{- if .Values.namespaces }}
    {{- range $k, $v := .Values.namespaces }}
    {{- if or $v.config_url $v.config_access_token }}
    [namespaces.{{ $k }}]
    {{- end }}
    {{- if $v.config_url }}
    config-url = {{ $v.config_url | quote }}
    {{- end }}
    {{- if $v.config_access_token }}
    config-access-token = {{ $v.config_access_token | quote }}
    {{- end }}
    {{- if or $v.registry $v.repository $v.user $v.password }}
    [namespaces.{{ $k }}.registry]
    {{- end }}
    {{- if $v.registry }}
    name = {{ $v.registry | quote }}
    {{- end }}
    {{- if $v.repository }}
    repository = {{ $v.repository | quote }}
    {{- end }}
    {{- if $v.user }}
    user = {{ $v.user | quote }}
    {{- end }}
    {{- if $v.password }}
    password = {{ $v.password | quote }}
    {{- end }}
    {{ end }}
    {{- else }}
    [namespaces]
    {{- end }}
