apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
data:
  operator-config.toml: |
    {{- if .Values.namespaces }}
    {{- range $k, $v := .Values.namespaces }}
    [namespaces.{{ $k }}]
    config_url = {{ $v.config_url | quote }}
    {{- if $v.config_access_token_env_var }}
    config_access_token_env_var = {{ $v.config_access_token_env_var | quote }}
    {{- end }}

    [namespaces.{{ $k }}.registry]
    type = "oci"
    registry = {{ $v.registry | quote }}
    repository = {{ $v.repository | quote }}
    user_env_var = {{ $v.user_env_var | quote }}
    password_env_var = {{ $v.password_env_var | quote }}
    {{ end }}
    {{- else }}
    [namespaces]
    {{- end }}
