{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pharia-kernel.fullname" . }}
  labels:
    {{- include "pharia-kernel.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      path: /
      port: metrics
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "pharia-kernel.selectorLabels" . | nindent 6 }}
{{- end }}
