global:
  phariaAIConfigMap: ""
  imagePullSecretName: ""
  # Global config for all ingress resources
  ingress:
    # -- The ingressClassName globally defined for all ingress resources.
    #    See also: https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
    ingressClassName: nginx
    # -- Domain for external access / ingress to Pharia AI services via {service}.{domain}
    #    e.g. {service}.pharia-ai.example.com
    ingressDomain: local
    # -- Additional annotations globally defined for all ingress-resources. This can be used to add ingress controller specific annotations.
    additionalAnnotations: {}
backwardsCompatibility: false
image:
  registry: alephalpha.jfrog.io
  repository: alephalpha.jfrog.io/container-images/pharia-kernel
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

envVars:
  values:
    AUTHORIZATION_URL: "{{ .Values.authorizationAddress }}"
    DOCUMENT_INDEX_URL: "{{ .Values.documentIndexAddress }}"
    INFERENCE_URL: "{{ .Values.inferenceAddress }}"
    LOG_LEVEL: "{{ .Values.logLevel }}"
    OTEL_ENDPOINT: "{{ .Values.openTelemetryEndpoint }}"
    OTEL_SAMPLING_RATIO: "{{ .Values.openTelemetrySamplingRatio }}"
    WASMTIME_CACHE_DIR: "/app/.cache"
  configmap:
    AUTHORIZATION_URL:
      name: "{{ .Values.global.phariaAIConfigMap }}"
      key: "PHARIA_IAM_URL"
    INFERENCE_URL:
      name: "{{ .Values.global.phariaAIConfigMap }}"
      key: "API_SCHEDULER_URL"
    DOCUMENT_INDEX_URL:
      name: "{{ .Values.global.phariaAIConfigMap }}"
      key: "DOCUMENT_INDEX_URL"
  resourceFields:
    MEMORY_REQUEST:
      resource: requests.memory
    MEMORY_LIMIT:
      resource: limits.memory
    WASMTIME_CACHE_SIZE_REQUEST:
      resource: requests.ephemeral-storage
    WASMTIME_CACHE_SIZE_LIMIT:
      resource: limits.ephemeral-storage

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 15
  failureThreshold: 2
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 2

nameOverride: pharia-kernel
fullnameOverride: pharia-kernel
imagePullSecrets: []
podAnnotations: {}
podLabels:
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 2000
  runAsGroup: 2000
containerSecurityContext:
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
securityContext:
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 80
  portName: http
  targetPort: 8081
  targetPortName: http
  protocol: TCP
  metricsPort: 9000
  metricsPortName: metrics
  metricsTargetPort: 9000
  metricsTargetPortName: metrics
  metricsProtocol: TCP

serviceMonitor:
  enabled: false
# -- Specify the default namespaces for PhariaKernel, which provide the default skills.
# If the default namespaces are configured, any duplicate namespaces in `pharia-kernel.namespaces` are ignored
# because these are backed by environment variables, which have higher precedence.
# For each default namespace, the following values need to be provided in the PhariaAI ConfigMap:
# - NAMESPACES__<NAMESPACE>__CONFIG_URL: URL to the namespace configuration
# - NAMESPACES__<NAMESPACE>__REGISTRY: Skill registry of the namespace
# - NAMESPACES__<NAMESPACE>__BASE_REPOSITORY: Base repository of the namespace
# The credentials for accessing the skill registries are retrieved from `registryUser` and `registryPassword` in
# the Secret configured as `global.imagePullOpaqueSecretName`.
defaultNamespaces: []
# -- Active namespaces for PhariaKernel. e.g.:
# playground:
#   configUrl: "https://gitlab.aleph-alpha.de/api/v4/projects/997/repository/files/namespace.toml/raw?ref=main"
#   configAccessToken: "GITLAB_CONFIG_ACCESS_TOKEN"
#   registry: "registry.gitlab.aleph-alpha.de"
#   baseRepository: "engineering/pharia-kernel-playground/skills"
#   registryUser: "REGISTRY_USER"
#   registryPassword: "REGISTRY_PASSWORD"
# Each of the value can alternatively be provided as environment variables, which have higher precedence:
# NAMESPACES__PLAYGROUND__CONFIG_URL
# NAMESPACES__PLAYGROUND__CONFIG_ACCESS_TOKEN
# NAMESPACES__PLAYGROUND__REGISTRY
# NAMESPACES__PLAYGROUND__BASE_REPOSITORY
# NAMESPACES__PLAYGROUND__REGISTRY_USER
# NAMESPACES__PLAYGROUND__REGISTRY_PASSWORD
namespaces: {}
logLevel: info
# Address of an OpenTelemetry collector listening for gRPC requests.
openTelemetryEndpoint: ""
# Sampling ratio between 0.0 and 1.0, where 0.0 means no sampling and 1.0 means all traces
openTelemetrySamplingRatio: ""
authorizationAddress: ""
inferenceAddress: ""
documentIndexAddress: ""

ingress:
  enabled: true
  hostname: pharia-kernel
  annotations: {}
  tls:
    enabled: false
    secretName: ""
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, add the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: "1"
#   memory: 4Gi
# requests:
#   cpu: 500m
#   memory: 2Gi
resources:
  limits:
    cpu: "4"
    memory: 8Gi
    ephemeral-storage: 8Gi
  requests:
    cpu: "2"
    memory: 4Gi
    ephemeral-storage: 4Gi
volumes:
  - name: config-volume
    configMap:
      name: pharia-kernel-config
  - name: ephemeral
    emptyDir:
      sizeLimit: 4Gi
volumeMounts:
  - name: config-volume
    mountPath: /app/config.toml
    subPath: config.toml
    readOnly: true
  - name: ephemeral
    mountPath: /app/.cache

# volume mounts required for securityContext.readOnlyRootFilesystem: true
extraVolumeMounts:
  - name: config-volume
    mountPath: /app/config.toml
    subPath: config.toml
    readOnly: true
  - name: ephemeral
    mountPath: /app/.cache

extraVolumes:
  - name: config-volume
    configMap:
      name: pharia-kernel-config
  - name: ephemeral
    emptyDir:
      sizeLimit: 4Gi
