{
 "title": "Pharia Kernel",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Metrics Source", "query": "prometheus" },
   { "name": "logs_source", "label": "Logs Source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Skill Executions per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(cluster, namespace, name, status) (increase(kernel_skill_execution_total[1m]))",
     "legendFormat": "{{cluster}} {{namespace}}/{{name}} -> {{status}}"
    }
   ]
  },
  {
   "title": "Skill Execution Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kernel_skill_execution_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(method, path, status) (increase(kernel_http_requests_total[1m]))",
     "legendFormat": "{{method}} {{path}} -> {{status}}"
    }
   ]
  },
  {
   "title": "Requests in Last Minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (round(increase(kernel_http_requests_total[1m])))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(kernel_http_requests_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CSI Usage Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(function) (increase(kernel_csi_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without (cpu) (increase(container_cpu_usage_seconds_total{container=~\"pharia-kernel\"}[1m])) / 60 / count without (cpu) (container_cpu_usage_seconds_total{container=~\"pharia-kernel\"})",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{container=~\"pharia-kernel\"}",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs ${logs_source}",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 54 },
     "repeat": "logs_source",
     "targets": [
      {
       "expr": "{container=\"pharia-kernel\"} !~ `matched_path.+=.+\"/health\"`"
      }
     ]
    }
   ]
  }
 ]
}