[package]
name = "test-skills"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
change-case = "0.2.0"
tempfile = "3.13.0"
wasi-preview1-component-adapter-provider = "25.0.1"
wit-component = "0.219.1"

[lints]
workspace = true
