[package]
name = "sample_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.93"
serde_json = "1.0.128"
serde = { version = "1", features = ["derive"] }
wit-bindgen = "0.35.0"
rand = "0.8.5"

[lib]
crate-type = ["cdylib"]
