[package]
name = "invalid-output"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wit-bindgen = "0.44.0"


[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
