name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-tools,cargo-nextest
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: cargo nextest run --workspace --all-features
      - run: cargo test --doc
    env:
      NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY: ghcr.io
      NAMESPACES__PHARIA_KERNEL_TEAM__BASE_REPOSITORY: aleph-alpha/pharia-kernel
      NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_USER: ${{ github.actor }}
      NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      PHARIA_AI_TOKEN: ${{ secrets.PHARIA_AI_TOKEN }}
      INFERENCE_URL: https://inference-api.product.pharia.com
      AUTHORIZATION_URL: https://pharia-iam.product.pharia.com

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  test-and-deploy-if-main-or-tag:
    runs-on: ubuntu-latest
    needs: [tests, lints]
    concurrency: test-and-deploy-if-main-or-tag-${{ github.ref }}
    permissions:
      contents: read
      id-token: write
    env:
      ARTIFACTORY_URL: https://alephalpha.jfrog.io
      ARTIFACTORY_HOST: alephalpha.jfrog.io
      ARTIFACTORY_REPOSITORY: alephalpha.jfrog.io/pharia-kernel-images
      ARTIFACTORY_HELM_REPOSITORY: pharia-kernel-helm
    steps:
      - uses: actions/checkout@v4
      - name: Generate image ID
        id: generate-image-id
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "IMAGE_ID=$(echo ${{ github.ref_name }} | cut -dv -f2)" >> $GITHUB_ENV
          else
            echo "IMAGE_ID=$(date +%F)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Log in to GitLab to access shared images
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.aleph-alpha.de
          username: ${{ secrets.GITLAB_USER }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build container
        uses: docker/build-push-action@v6
        id: build-image
        with:
          load: true
          pull: true
          push: false
          file: ./Containerfile
          tags: pharia-kernel:latest, pharia-kernel:${{ env.IMAGE_ID }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Container test
        run: bash -x ./tests/test-container.sh pharia-kernel:$IMAGE_ID

      - name: Integration test
        run: |
          (podman run -p 8081:8081 -v ./config.toml:/app/config.toml \
            -e NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_USER=dummy \
            -e NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_PASSWORD=dummy \
            -e NAMESPACES__PHARIA_KERNEL_TEAM__CONFIG_ACCESS_TOKEN=dummy \
            -e PHARIA_AI_TOKEN=dummy \
            pharia-kernel:$IMAGE_ID | cat) &
          bash -x ./tests/test-image.sh 8081 127.0.0.1

      - name: Create kind cluster with registry
        id: kind
        uses: helm/kind-action@v1
        with:
          registry: true
          registry_name: local-registry
          registry_port: 5001

      - name: Push to local registry
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./Containerfile
          tags: ${{ steps.kind.outputs.LOCAL_REGISTRY }}/pharia-kernel:${{ env.IMAGE_ID }}

      - name: Test Helm chart
        env:
          LOCAL_REGISTRY: ${{ steps.kind.outputs.LOCAL_REGISTRY }}
        run: |
          kubectl cluster-info
          kubectl get storageclass standard

          helm install pharia-kernel helm-charts/pharia-kernel \
              -f helm-charts/pharia-kernel/values-kind.yaml \
              --set "image.repository=$LOCAL_REGISTRY/pharia-kernel" \
              --set "image.tag=$IMAGE_ID" \
              --set "namespaces.playground.configAccessToken=${{ secrets.PLAYGROUND_GITLAB_TOKEN }}" \
              --set "namespaces.playground.registryUser=${{ secrets.PLAYGROUND_GITLAB_USER }}" \
              --set "namespaces.playground.registryPassword=${{ secrets.PLAYGROUND_GITLAB_TOKEN }}" \
              --wait --timeout 10m
          helm test pharia-kernel

          kubectl port-forward service/pharia-kernel 8082:80 &

          while ! nc -vz localhost 8082 > /dev/null 2>&1 ; do
            echo "Waiting for port-forward to be ready..."
            sleep 0.1
          done

          ./tests/test-list-skills.sh "${{ secrets.PHARIA_AI_TOKEN }}" http://127.0.0.1:8082
          ./tests/test-run-skill.sh "${{ secrets.PHARIA_AI_TOKEN }}" http://127.0.0.1:8082

      - uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ steps.kind.outputs.LOCAL_REGISTRY }}/pharia-kernel:${{ env.IMAGE_ID }}
          trivyignores: ".trivyignore"
          severity: "MEDIUM,HIGH,CRITICAL"
          exit-code: "1"

      - if: github.event_name != 'pull_request'
        name: Get JFrog Artifactory login credentials
        uses: ./.github/actions/jfrog

      - if: github.event_name != 'pull_request'
        name: Log in to JFrog Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ARTIFACTORY_REPOSITORY }}
          username: ${{ env.JFROG_ACCESS_TOKEN_SUBJECT }}
          password: ${{ env.JFROG_ACCESS_TOKEN }}

      - if: github.event_name != 'pull_request'
        name: Push to JFrog Artifactory
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./Containerfile
          tags: ${{ env.ARTIFACTORY_REPOSITORY }}/pharia-kernel:latest, ${{ env.ARTIFACTORY_REPOSITORY }}/pharia-kernel:${{ env.IMAGE_ID }}

      - if: github.event_name != 'pull_request'
        name: Print image URL
        run: echo "Image pushed to ${{ steps.push.outputs.registry-paths }}"

      - if: github.event_name != 'pull_request'
        name: Get user name and email
        run: |
          echo "TRIGGER_USER_NAME=$(git log -n 1 --pretty=format:%aN)" >> $GITHUB_ENV
          echo "TRIGGER_USER_EMAIL=$(git log -n 1 --pretty=format:%aE)" >> $GITHUB_ENV

      - if: github.event_name != 'pull_request'
        name: Update image tag
        uses: digital-blueprint/gitlab-pipeline-trigger-action@v1
        with:
          host: "gitlab.aleph-alpha.de"
          trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          id: "931"
          ref: "main"
          variables: '{"TRIGGER_USER_EMAIL":"${{ env.TRIGGER_USER_EMAIL }}","TRIGGER_USER_NAME":"${{ env.TRIGGER_USER_NAME }}","TRIGGER_IMAGE_TAG":"${{ env.IMAGE_ID }}","TRIGGER_IMAGE_TAG_TARGET":".image.tag","UPDATE_DIRECTORY":"applications","UPDATE_PROJECT":"pharia-kernel"}'

      - if: github.ref_type == 'tag'
        name: Extract Helm chart version
        run: echo "CHART_VERSION=$(yq .version < helm-charts/pharia-kernel/Chart.yaml)" >> $GITHUB_ENV

      - if: github.ref_type == 'tag'
        name: Publish Helm chart changelog
        run: |
          CHANGELOG_FILE=Changelog-pharia-kernel-$CHART_VERSION.md
          curl --location --header "PRIVATE-TOKEN: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN }}" \
            --upload-file helm-charts/pharia-kernel/changelogs/$CHANGELOG_FILE \
            "https://gitlab.aleph-alpha.de/api/v4/projects/1139/packages/generic/changelogs/pharia-ai/$CHANGELOG_FILE"

      - if: github.ref_type == 'tag'
        name: Push Helm charts
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: pharia-kernel
          repository: ${{ env.ARTIFACTORY_HELM_REPOSITORY }}
          tag: ${{ env.CHART_VERSION }}
          path: helm-charts/pharia-kernel
          registry: ${{ env.ARTIFACTORY_HOST }}
          registry_username: ${{ env.JFROG_ACCESS_TOKEN_SUBJECT }}
          registry_password: ${{ env.JFROG_ACCESS_TOKEN }}
