name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-tools
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run cargo test
        run: cargo test --workspace --all-features
    env:
      NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY: ghcr.io
      NAMESPACES__PHARIA_KERNEL_TEAM__BASE_REPOSITORY: aleph-alpha/pharia-kernel
      NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_USER: ${{ github.actor }}
      NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_PASSWORD: ${{ secrets.SKILL_REGISTRY_PASSWORD }}
      PHARIA_AI_TOKEN: ${{ secrets.PHARIA_AI_TOKEN }}
      INFERENCE_URL: https://inference-api.product.pharia.com
      AUTHORIZATION_URL: https://pharia-iam.product.pharia.com

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  test-and-deploy-if-main-or-tag:
    runs-on: ubuntu-latest
    needs: [tests, lints]
    concurrency: test-and-deploy-if-main-or-tag-${{ github.ref }}
    permissions:
      contents: read
      id-token: write
    env:
      ARTIFACTORY_URL: https://alephalpha.jfrog.io
      ARTIFACTORY_HOST: alephalpha.jfrog.io
      ARTIFACTORY_REPOSITORY: alephalpha.jfrog.io/pharia-kernel-images
      ARTIFACTORY_HELM_REPOSITORY: pharia-kernel-helm
    steps:
      - uses: actions/checkout@v4
      - name: Generate image ID
        id: generate-image-id
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "IMAGE_ID=$(echo ${{ github.ref_name }} | cut -dv -f2)" >> $GITHUB_ENV
          else
            echo "IMAGE_ID=$(date +%F)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Log in to GitLab to access shared images
        uses: redhat-actions/podman-login@v1
        with:
          registry: registry.gitlab.aleph-alpha.de
          username: ${{ secrets.GITLAB_USER }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: pharia-kernel
          tags: latest ${{ env.IMAGE_ID }}
          oci: true
          containerfiles: |
            ./Containerfile

      - name: Container test
        run: bash -x ./tests/test-container.sh pharia-kernel:$IMAGE_ID

      - name: Integration test
        run: |
          (podman run -p 8081:8081 -v ./config.toml:/app/config.toml \
            -e NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_USER=dummy \
            -e NAMESPACES__PHARIA_KERNEL_TEAM__REGISTRY_PASSWORD=dummy \
            -e NAMESPACES__PHARIA_KERNEL_TEAM__CONFIG_ACCESS_TOKEN=dummy \
            -e PHARIA_AI_TOKEN=dummy \
            pharia-kernel:$IMAGE_ID | cat) &
          bash -x ./tests/test-image.sh 8081 127.0.0.1

      - if: github.event_name != 'pull_request'
        name: Get JFrog Artifactory login credentials
        uses: ./.github/actions/jfrog

      - if: github.event_name != 'pull_request'
        name: Log in to JFrog Artifactory
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.ARTIFACTORY_REPOSITORY }}
          username: ${{ env.JFROG_ACCESS_TOKEN_SUBJECT }}
          password: ${{ env.JFROG_ACCESS_TOKEN }}

      - if: github.event_name != 'pull_request'
        name: Push to JFrog Artifactory
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.ARTIFACTORY_REPOSITORY }}

      - if: github.event_name != 'pull_request'
        name: Print image URL
        run: echo "Image pushed to ${{ steps.push.outputs.registry-paths }}"

      - if: github.event_name != 'pull_request'
        name: Get user name and email
        run: |
          echo "TRIGGER_USER_NAME=$(git log -n 1 --pretty=format:%aN)" >> $GITHUB_ENV
          echo "TRIGGER_USER_EMAIL=$(git log -n 1 --pretty=format:%aE)" >> $GITHUB_ENV

      - if: github.event_name != 'pull_request'
        name: Update image tag
        uses: digital-blueprint/gitlab-pipeline-trigger-action@v1
        with:
          host: "gitlab.aleph-alpha.de"
          trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          id: "931"
          ref: "main"
          variables: '{"TRIGGER_USER_EMAIL":"${{ env.TRIGGER_USER_EMAIL }}","TRIGGER_USER_NAME":"${{ env.TRIGGER_USER_NAME }}","TRIGGER_IMAGE_TAG":"${{ env.IMAGE_ID }}","TRIGGER_IMAGE_TAG_TARGET":".image.tag","UPDATE_DIRECTORY":"applications","UPDATE_PROJECT":"pharia-kernel"}'

      - if: github.ref_type == 'tag'
        name: Extract Helm chart version
        run: echo "CHART_VERSION=$(yq .version < helm-charts/pharia-kernel/Chart.yaml)" >> $GITHUB_ENV

      - if: github.ref_type == 'tag'
        name: Push Helm charts
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: pharia-kernel
          repository: ${{ env.ARTIFACTORY_HELM_REPOSITORY }}
          tag: ${{ env.CHART_VERSION }}
          path: helm-charts/pharia-kernel
          registry: ${{ env.ARTIFACTORY_HOST }}
          registry_username: ${{ env.JFROG_ACCESS_TOKEN_SUBJECT }}
          registry_password: ${{ env.JFROG_ACCESS_TOKEN }}
