name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  ARTIFACTORY_URL: https://alephalpha.jfrog.io
  CARGO_REGISTRY_INDEX: sparse+https://alephalpha.jfrog.io/artifactory/api/cargo/pharia-kernel-crates/index/

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@v4

      - if: ${{ steps.release.outputs.release_created }}
        name: Checkout repository
        uses: actions/checkout@v4

      - if: ${{ steps.release.outputs.release_created }}
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - if: ${{ steps.release.outputs.release_created }}
        name: Get JFrog Artifactory login credentials
        uses: ./.github/actions/jfrog

      - if: ${{ steps.release.outputs.release_created }}
        name: Publish to JFrog crates registry
        run: cargo publish -p pharia-kernel --index "$CARGO_REGISTRY_INDEX" --token "Bearer $JFROG_ACCESS_TOKEN"
